# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: nit-solvency
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  versionFunctions: false

# you can overwrite defaults here
#  stage: dev
#

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  GetNitSolvency:
    handler: handler.GetNitSolvency
    events:
      - http:
          path: solvency/{nit}
          method: get
          request:
            parameters:
              paths:
                nit: true
    environment:
      NIT_SOLVENCY_URL: ${env:NIT_SOLVENCY_URL}
    layers:
      # Google Chrome for AWS Lambda as a layer
      # https://github.com/shelfio/chrome-aws-lambda-layer
      - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:10
    memorySize: 2048 # recommended
    timeout: 30
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
plugins:
  - serverless-dotenv-plugin
